---
- name: Ensure Sublime-Text is installed
  homebrew: "name=sublime-text state=absent"

- name: sync all Plugins and Configs into Folder
  synchronize:
    src: "Library/Packages/"
    dest: "~/Library/Application Support/Sublime Text 3/Packages/"

- name: install CSS-Linter via NPM
  command: npm install -g csslint

